// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYCfvoq1ipaxFqCVVzg6ljOKRpwgFsZ8',
    appId: '1:923322418087:web:3b18f93ae5f80cdc43ac82',
    messagingSenderId: '923322418087',
    projectId: 'englishkidsapp-916be',
    authDomain: 'englishkidsapp-916be.firebaseapp.com',
    storageBucket: 'englishkidsapp-916be.firebasestorage.app',
    measurementId: 'G-6RGSPPCX66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSpwmDuTjDYgEQjgRqF0Zjb-aXh9AZcdk',
    appId: '1:923322418087:android:a616efff0e5b8f4d43ac82',
    messagingSenderId: '923322418087',
    projectId: 'englishkidsapp-916be',
    storageBucket: 'englishkidsapp-916be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF9cUAujEsyWDTlshrh2ejuXMcDpW61rk',
    appId: '1:923322418087:ios:bfe054434113b41a43ac82',
    messagingSenderId: '923322418087',
    projectId: 'englishkidsapp-916be',
    storageBucket: 'englishkidsapp-916be.firebasestorage.app',
    iosBundleId: 'com.example.englishAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF9cUAujEsyWDTlshrh2ejuXMcDpW61rk',
    appId: '1:923322418087:ios:bfe054434113b41a43ac82',
    messagingSenderId: '923322418087',
    projectId: 'englishkidsapp-916be',
    storageBucket: 'englishkidsapp-916be.firebasestorage.app',
    iosBundleId: 'com.example.englishAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFYCfvoq1ipaxFqCVVzg6ljOKRpwgFsZ8',
    appId: '1:923322418087:web:2d23240705ef246f43ac82',
    messagingSenderId: '923322418087',
    projectId: 'englishkidsapp-916be',
    authDomain: 'englishkidsapp-916be.firebaseapp.com',
    storageBucket: 'englishkidsapp-916be.firebasestorage.app',
    measurementId: 'G-GFV3QLCJ5K',
  );

}