// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2SkzGa4_IscUyCxOLW0EPD-q2KEbJDt8',
    appId: '1:869502851227:web:438df7c0049a5d6cec8e3e',
    messagingSenderId: '869502851227',
    projectId: 'englishkidsapp-fe0af',
    authDomain: 'englishkidsapp-fe0af.firebaseapp.com',
    storageBucket: 'englishkidsapp-fe0af.firebasestorage.app',
    measurementId: 'G-CDBN0H0YXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm9glf6JeaaTffQX2uhirqGO4V8ez8Vew',
    appId: '1:869502851227:android:b17f43ae4d2aeba9ec8e3e',
    messagingSenderId: '869502851227',
    projectId: 'englishkidsapp-fe0af',
    storageBucket: 'englishkidsapp-fe0af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVNzyPAdH-ewHg_4ZfHo-Oc3D_jVtg128',
    appId: '1:869502851227:ios:00510e07f815c873ec8e3e',
    messagingSenderId: '869502851227',
    projectId: 'englishkidsapp-fe0af',
    storageBucket: 'englishkidsapp-fe0af.firebasestorage.app',
    iosBundleId: 'com.example.englishAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVNzyPAdH-ewHg_4ZfHo-Oc3D_jVtg128',
    appId: '1:869502851227:ios:00510e07f815c873ec8e3e',
    messagingSenderId: '869502851227',
    projectId: 'englishkidsapp-fe0af',
    storageBucket: 'englishkidsapp-fe0af.firebasestorage.app',
    iosBundleId: 'com.example.englishAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2SkzGa4_IscUyCxOLW0EPD-q2KEbJDt8',
    appId: '1:869502851227:web:ce467d39fe676844ec8e3e',
    messagingSenderId: '869502851227',
    projectId: 'englishkidsapp-fe0af',
    authDomain: 'englishkidsapp-fe0af.firebaseapp.com',
    storageBucket: 'englishkidsapp-fe0af.firebasestorage.app',
    measurementId: 'G-0B3JLFJ11J',
  );
}
